pipeline {
    agent {
        kubernetes {
            label 'k8s-agent'
        }
    }

    stages {
        stage('a') {
            steps {
                script {
                    println 'hello world'
                }
            }
        }
    }
}
