pipeline {
    agent {
        kubernetes {
            label 'docker-agent'
        }
    }

    stages {
        stage('build image') {
            steps {
                script {
                    sh "docker build"
                }
            }
        }
    }
}
