apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::891377277112:role/eksctl-dev-cluster-nodegroup-dev-n-NodeInstanceRole-WmILNaPiYTSO

