replicaCount: 1
namespace: prod
appName: basic-to-do-client

image:
  repository: volk22kaimn/basic-to-do-client
  tag: "3.1.v2"

selector:
  appName: basic-to-do-client
 
container:
  port:
    name: http 

service:
  portName: todo-client
  port: 80
  type: NodePort

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

env:
  enabled: true
  variables:
    - name: API_URL
      value: "http://206.81.16.246:30828/api"

command:
  enabled: true
  command:
    - "/bin/sh"
  args:
    - "-c"
    - |
      echo "window._env_ = { API_URL: \"${API_URL}\" };" > /usr/share/nginx/html/config.js && exec nginx -g 'daemon off;'


environment: dev

networkPolicy:
  enabled: false

ingress:
  enabled: false
  name: to-do-ingress
  host: "volk.todo.org"
  path: /
  serviceName: basic-to-do-client

hpa:
  cpuUtilization: 70
  minReplicas: 2
  maxReplicas: 10
