replicaCount: 1
namespace: dev
appName: basic-to-do-client

image:
  repository: volk22kaimn/basic-to-do-client
  tag: "1.1.7"

selector:
  appName: basic-to-do-client

container:
  port:
    name: http 

service:
  portName: todo-client
  port: 80
  type: NodePort

env: 
  enabled: false

environment: production

networkPolicy:
  enabled: false

ingress:
  enabled: false
  name: to-do-ingress
  host: "volk.todo.org"
  path: /
  serviceName: basic-to-do-client
