replicaCount: 1

appName: basic-to-do-client

image:
  repository: volk22kaimn/basic-to-do-client
  tag: "1.1.5"

selector:
  appName: basic-to-do-client

container:
  port:
    name: http 

service:
  portName: todo-client
  port: 80
  type: NodePort

env: 
  enabled: false

environment: production
