replicaCount: 2
namespace: dev
appName: basic-to-do-client

image:
  repository: volk22kaimn/basic-to-do-client
  tag: "1.2.1"

selector:
  appName: basic-to-do-client
 
container:
  port:
    name: http 

service:
  enabled: true
  portName: todo-client
  port: 80
  type: ClusterIP
aws:
  annotation: false
  type: "alb"
  scheme: "internet-facing" 

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

env: 
  enabled: false

environment: production

networkPolicy:
  enabled: false

ingress:
  enabled: false
  name: basic-to-do-ingress
  host: "volk.todo.org"
  path: /
  serviceName: basic-to-do-client

hpa:
  cpuUtilization: 70
  minReplicas: 1
  maxReplicas: 10