replicaCount: 2
namespace: dev
appName: basic-to-do-client

image:
  repository: volk22kaimn/basic-to-do-client
  tag: "1.1.6"

selector:
  appName: basic-to-do-client
 
container:
  port:
    name: http 

service:
  portName: todo-client
  port: 80
  type: NodePort

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "1Gi"
    memory: "1Gi"

env: 
  enabled: false

environment: production

networkPolicy:
  enabled: false

ingress:
  enabled: false
  name: to-do-ingress
  host: "volk.todo.org"
  path: /
  serviceName: basic-to-do-client
