replicaCount: 1
namespace: dev
appName: basic-to-do-db

image:
  repository: mongo
  tag: "latest"

selector:
  appName: basic-to-do-db

container:
  port:
    name: http 

service:
  portName: mongodb
  port: 27017
  type: ClusterIP

env: 
  enabled: false
  
environment: production

networkPolicy:
  enabled: true
  name: mongodb-network-policy
  namespace: dev
  toPodLabels:
    - key: appName
      value: basic-to-do-db
  fromPodLabels: 
    - key: appName
      value: basic-to-do-server


ingress:
  enabled: false