replicaCount: 1
namespace: dev
appName: basic-to-do-db

image:
  repository: mongo
  tag: "latest"

selector:
  appName: basic-to-do-db

container:
  port:
    name: http 

service:
  portName: mongodb
  port: 27017
  type: ClusterIP

env: 
  enabled: false
  
environment: production
