replicaCount: 1
namespace: prod
appName: basic-to-do-server

image:
  repository: volk22kaimn/basic-to-do-server
  tag: "3.2.v2"

selector:
  appName: basic-to-do-server

container:
  port:
    name: http 

readinessProbe:
  enabled: true
  path: /health
  port: 3000
  initialDelaySeconds: 5
  periodSeconds: 5



strategy:
  enabled: true

updateStrategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0


service:
  portName: todo-server
  port: 3000
  type: NodePort
  nodePort: 30828

env: 
  enabled: true
  variables:
  - name: MONGODB_URI
    value: mongodb://basic-to-do-db:27017/todoapp

command:
  enabled: false

environment: dev

networkPolicy:
  enabled: false
  

ingress:
  enabled: false
