replicaCount: 1
namespace: dev
appName: basic-to-do-server

image:
  repository: volk22kaimn/basic-to-do-server
  tag: "1.1.0"

selector:
  appName: basic-to-do-server

container:
  port:
    name: http 

service:
  portName: todo-server
  port: 3000
  type: NodePort
  nodePort: 30826

env: 
  enabled: true
  variables:
  - name: MONGODB_URI
    value: mongodb://basic-to-do-db:27017/todoapp

environment: production

networkPolicy:
  enabled: false
  

ingress:
  enabled: false