pipeline {
    agent {
        kubernetes {
            label 'kaniko-git-mongo-node'
            defaultContainer 'kaniko'
        }
    }

    parameters {
        string(name: 'BRANCH_NAME', defaultValue: 'master', description: 'Git branch to build from')
    }

    stages {
        stage('Clone') {
            steps {
                container('git') {
                    cleanWs()
                    sh """
                      git clone -b ${params.BRANCH_NAME} https://github.com/volk22kamin/basicToDoApp.git .
                  """
                }
            }
        }
        stage("Test") {
            steps {
                script {
                    container("node") {
                        dir("server") {
                            sh "npm install"
                            sh "npm test"
                        }
                    }
                }
            }
        }
        stage('Build and Push') {
            steps {
                script {
                    container('kaniko') {
                        String tag = null
                        dir('basic-to-do-app') {
                            String valuesFile = 'server-values.yaml'
                            def yaml = readYaml file: valuesFile
                            tag = yaml.image.tag
                        }
                        if (tag != null) {
                            sh """
                                /kaniko/executor \
                                --context=./server \
                                --dockerfile=./server/Dockerfile \
                                --destination=volk22kaimn/basic-to-do-server:${tag}
                            """
                            currentBuild.displayName = "Build #${env.BUILD_NUMBER} - tag: ${tag}"
                        }
                    }
                }
            }
        }
    }
}