apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      appName: {{ .Values.selector.appName }}
  template:
    metadata:
      labels:
        appName: {{ .Values.selector.appName }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
              name: {{ .Values.container.port.name }}
          env:
            - name: ENVIRONMENT
              value: {{ .Values.environment | quote }}
