{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.networkPolicy.name }}
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      {{- range $key, $val := .Values.networkPolicy.toPodLabels }}
      {{ $key }}: {{ $val }}-{{ $.Values.environment }}
      {{- end }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- range $key, $val := .Values.networkPolicy.fromPodLabels }}
          {{ $key }}: {{ $val }}-{{ $.Values.environment }}
          {{- end }}
{{- end }}
