{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    appName: {{ .Values.selector.appName }}
  {{- if .Values.aws.annotation }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "{{ .Values.aws.type }}"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "{{ .Values.aws.scheme }}"
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    appName: {{ .Values.selector.appName }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
{{- end }}
