{{- if .Values.dynamicService }}
apiVersion: v1
kind: Service
metadata:
  name: basic-to-do-client-blue
  namespace: prod
  labels:
    appName: basic-to-do-client-blue
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: todo-client
  selector:
    appName: basic-to-do-client-blue
{{- else }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-{{ .Values.environment }}
  namespace: {{ .Values.namespace }}
  labels:
    appName: {{ .Values.selector.appName }}-{{ .Values.environment }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: {{ .Values.service.portName }}
  selector:
    appName: {{ .Values.selector.appName }}-{{ .Values.environment }}
{{- end }}